Repository Runroom/runroom-packages, pull requests merged in 2022-09, with the labels that each got.

#128 [All] Allow `doctrine/persistence` ^3.0, `sonata-project/doctrine-extensions` ^2.0 and `sonata-project/twig-extensions` ^2.0
  composer.json
  monorepo-builder.php
  packages/basic-page-bundle/composer.json
  packages/basic-page-bundle/src/Repository/BasicPageRepository.php
  packages/ckeditor-sonata-media-bundle/composer.json
  packages/cookies-bundle/composer.json
  packages/cookies-bundle/src/Repository/CookiesPageRepository.php
  packages/cookies-bundle/tests/App/Kernel.php
  packages/redirection-bundle/composer.json
  packages/redirection-bundle/src/Repository/RedirectRepository.php
  packages/seo-bundle/composer.json
  packages/seo-bundle/src/Repository/MetaInformationRepository.php
  packages/seo-bundle/tests/App/Kernel.php
  packages/sortable-behavior-bundle/composer.json
  packages/sortable-behavior-bundle/src/Service/PositionHandlerInterface.php
  packages/testing/composer.json
  packages/translation-bundle/composer.json
  packages/translation-bundle/src/Repository/TranslationRepository.php
  packages/translation-bundle/tests/App/Kernel.php
  packages/user-bundle/composer.json
  packages/user-bundle/src/Command/ActivateUserCommand.php
  packages/user-bundle/src/Command/ChangePasswordCommand.php
  packages/user-bundle/src/Command/CreateUserCommand.php
  packages/user-bundle/src/Command/DeactivateUserCommand.php
  packages/user-bundle/src/Controller/ResetPasswordController.php
  packages/user-bundle/src/Security/UserProvider.php
  packages/user-bundle/tests/App/Kernel.php
  packages/user-bundle/tests/Unit/ChangePasswordFormTypeTest.php
  packages/user-bundle/tests/Unit/ResetPasswordRequestFormTypeTest.php
  packages/user-bundle/tests/Unit/UserProviderTest.php
  phpstan-baseline.neon
  tests/App/Kernel.php
  tests/App/services.php
Labels: dependencies

#129 [SortableBehaviorBundle] Add `SortableAdminTrait` to avoid the extend of `AbstractSortableAdmin`
  packages/sortable-behavior-bundle/src/Admin/AbstractSortableAdmin.php
  packages/sortable-behavior-bundle/src/Admin/SortableAdminTrait.php
Labels: feature

#131 [RunroomSortableBehaviorBundle] Add Usage guide on the README
  README.md
  packages/basic-page-bundle/README.md
  packages/ckeditor-sonata-media-bundle/README.md
  packages/cookies-bundle/README.md
  packages/form-handler-bundle/README.md
  packages/redirection-bundle/README.md
  packages/render-event-bundle/README.md
  packages/seo-bundle/README.md
  packages/sortable-behavior-bundle/README.md
  packages/testing/README.md
  packages/translation-bundle/README.md
  packages/user-bundle/README.md
Labels: docs

#132 [All] Allow to install vendors on inner packages
  packages/basic-page-bundle/composer.json
  packages/ckeditor-sonata-media-bundle/composer.json
  packages/cookies-bundle/composer.json
  packages/form-handler-bundle/composer.json
  packages/redirection-bundle/composer.json
  packages/seo-bundle/composer.json
  packages/sortable-behavior-bundle/composer.json
  packages/translation-bundle/composer.json
  packages/user-bundle/composer.json
Labels: dependencies

#133 [SortableBehaviorBundle] BC Break: Simplify Sortable Controller to be only an action auto configured on the route
  packages/sortable-behavior-bundle/README.md
  packages/sortable-behavior-bundle/composer.json
  packages/sortable-behavior-bundle/src/Action/MoveAction.php
  packages/sortable-behavior-bundle/src/Admin/SortableAdminTrait.php
  packages/sortable-behavior-bundle/src/Resources/config/admin.php
  packages/sortable-behavior-bundle/tests/App/Entity/SortableEntity.php
  packages/sortable-behavior-bundle/tests/App/Kernel.php
  packages/sortable-behavior-bundle/tests/App/routing.yaml
  packages/sortable-behavior-bundle/tests/App/services.php
  packages/sortable-behavior-bundle/tests/Functional/AbstractSortableAdminTest.php
  packages/sortable-behavior-bundle/tests/Integration/AbstractSortableAdminTest.php
  packages/sortable-behavior-bundle/tests/Integration/RunroomSortableBehaviorExtensionTest.php
  packages/sortable-behavior-bundle/tests/Unit/MoveActionTest.php
  packages/sortable-behavior-bundle/tests/Unit/ORMPositionHandlerTest.php
  psalm-baseline.xml
  tests/App/services.php
Labels: feature

#137 [RunroomCkeditorSonataMedia] Add functional tests
  composer.json
  packages/ckeditor-sonata-media-bundle/composer.json
  packages/ckeditor-sonata-media-bundle/src/Action/BrowserAction.php
  packages/ckeditor-sonata-media-bundle/src/Action/UploadAction.php
  packages/ckeditor-sonata-media-bundle/src/Admin/MediaAdminExtension.php
  packages/ckeditor-sonata-media-bundle/tests/App/.gitignore
  packages/ckeditor-sonata-media-bundle/tests/App/Kernel.php
  packages/ckeditor-sonata-media-bundle/tests/App/routing.yaml
  packages/ckeditor-sonata-media-bundle/tests/Fixtures/file.png
  packages/ckeditor-sonata-media-bundle/tests/Functional/ActionsTest.php
  packages/user-bundle/composer.json
  tests/App/.gitignore
  tests/App/Kernel.php
Labels: tests
